CriteriaPermissionSetDescriptor: Do not use tclass for validation if it is a regex.
The validation function does not support regexes for the tclass parameter.
This will only verify that the permissions are valid for at least one
object class in the policy rather than trying to do regex matching
on classes and validating from there, as this typically duplicates
the analysis class functionality.

Fixes a traceback like this:

$ ./sesearch -A -s domain -ds -c socket -rc -p ioctl --debug
Traceback (most recent call last):
  File "/home/pebenito/projects/setools/./sesearch", line 172, in <module>
    terq.perms = args.perms.split(",")
  File "/home/pebenito/projects/setools/setools/descriptors.py", line 175, in __set__
    validate_perms_any(perms,
  File "/home/pebenito/projects/setools/setools/util.py", line 210, in validate_perms_any
    invalid -= c.perms
AttributeError: 're.Pattern' object has no attribute 'perms'

Signed-off-by: Chris PeBenito <pebenito@ieee.org>