libqpol: fix typos in documentation comments
clang warns about unknown documentation commands, which are spelling
errors:

    libqpol/include/qpol/cond_query.h:87:5: error: unknown command tag
    name 'returm'; did you mean 'return'?
    [-Werror,-Wdocumentation-unknown-command]
     *  @returm 0 on success and < 0 on failure; if the call fails,
        ^~~~~~~
         return